
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: zk-claims
      containers:
      - name: kubernetes-zookeeper
        imagePullPolicy: Always
        image: "localhost:32000/zk"
        resources:
          requests:
            memory: "0.75Gi"
            cpu: "0.25"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        volumeMounts:
        - name: datadir
          mountPath: /tmp/zookeeper
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
